# Generated by Django 2.2.5 on 2019-12-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_origin', models.CharField(max_length=255, unique=True)),
                ('country_iso', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['country_origin'],
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.country')),
            ],
        ),
        migrations.CreateModel(
            name='bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_id', models.CharField(max_length=6)),
                ('quantity', models.FloatField()),
                ('crop_time', models.CharField(max_length=120, null=True)),
                ('price_kg', models.FloatField()),
                ('purchase_out_turn', models.FloatField()),
                ('nut_count', models.IntegerField()),
                ('number_bag', models.FloatField(null=True)),
                ('production_out_turn', models.FloatField()),
                ('moisture', models.FloatField(null=True)),
                ('drying_req', models.BooleanField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.region')),
            ],
        ),
    ]
