# Generated by Django 2.2.5 on 2019-12-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='id',
        ),
        migrations.AddField(
            model_name='bucket',
            name='bucket_name',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='bucket_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
