# Generated by Django 2.2.5 on 2019-12-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0002_auto_20191208_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='bucket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
