# Generated by Django 2.2.5 on 2019-12-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0005_auto_20191208_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='day_type',
            fields=[
                ('day_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='climate_params',
            fields=[
                ('clim_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_climate', models.DateField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('humidity', models.FloatField(null=True)),
                ('day_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.day_type')),
            ],
        ),
    ]
