# Generated by Django 2.2.5 on 2019-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0007_auto_20191209_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing_lot',
            name='cook_pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='cook_time',
            field=models.FloatField(null=True),
        ),
    ]
