# Generated by Django 2.2.5 on 2019-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0008_auto_20191209_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing_lot',
            name='bag_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='foreign_particles',
            field=models.FloatField(null=True),
        ),
    ]
