# Generated by Django 2.2.5 on 2019-12-09 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0009_auto_20191209_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing_lot',
            name='date_of_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.climate_params'),
        ),
    ]
