# Generated by Django 2.2.5 on 2019-12-20 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0010_auto_20191209_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ['quantity']},
        ),
        migrations.CreateModel(
            name='cutting_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcn_moisture', models.FloatField()),
                ('wholes', models.FloatField()),
                ('pieces', models.FloatField()),
                ('rejections', models.FloatField()),
                ('shells_output', models.FloatField()),
                ('pending_quantity', models.FloatField(null=True)),
                ('pending', models.BooleanField()),
                ('foreign_particles', models.FloatField(null=True)),
                ('kernel_moisture', models.FloatField(null=True)),
                ('out_turn', models.FloatField(null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.climate_params')),
                ('lot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.processing_lot')),
            ],
        ),
    ]
