# Generated by Django 2.2.5 on 2019-12-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0011_auto_20191220_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting_section',
            name='pending',
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='processed',
            field=models.FloatField(null=True),
        ),
    ]
