# Generated by Django 2.2.5 on 2019-12-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0013_auto_20191222_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing_lot',
            name='out_turn',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='pieces',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='rejection',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='shells',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='wholes',
            field=models.FloatField(null=True),
        ),
    ]
