# Generated by Django 2.2.5 on 2019-12-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0014_auto_20191223_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing_lot',
            name='adj',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='lot_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='process_total',
            field=models.FloatField(null=True),
        ),
    ]
