# Generated by Django 2.2.5 on 2019-12-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0015_auto_20191223_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ['-quantity']},
        ),
        migrations.RenameField(
            model_name='processing_lot',
            old_name='adj',
            new_name='adj_cutting',
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='dried_pieces',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='dried_wholes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='final_ouput',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='husk',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='bormah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dried_wholes', models.FloatField()),
                ('dried_pieces', models.FloatField()),
                ('bormah_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.climate_params')),
                ('bormah_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.processing_lot')),
            ],
        ),
    ]
