# Generated by Django 2.2.5 on 2019-12-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0018_auto_20191225_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bormah',
            name='dried_pieces',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bormah',
            name='dried_wholes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='peeling',
            name='husk',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='peeling',
            name='rejections',
            field=models.FloatField(null=True),
        ),
    ]
