# Generated by Django 2.2.5 on 2019-12-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0019_auto_20191225_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade_names',
            fields=[
                ('grad_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade_type', models.CharField(max_length=10)),
                ('grade_names', models.CharField(max_length=10)),
            ],
        ),
    ]
