# Generated by Django 2.2.5 on 2019-12-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0020_grade_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='grading_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_output', models.CharField(max_length=1500)),
                ('grading_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.climate_params')),
                ('grading_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaju.processing_lot')),
            ],
        ),
    ]
