# Generated by Django 2.2.5 on 2020-01-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0021_grading_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade_names',
            name='consolidated_qty',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processing_lot',
            name='grading_consolidation',
            field=models.CharField(default='NA', max_length=1500),
        ),
    ]
