# Generated by Django 2.2.5 on 2020-01-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaju', '0022_auto_20200103_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing_lot',
            name='adj_cutting',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='bag_weight',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='cook_pressure',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='cook_time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='dried_pieces',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='dried_wholes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='final_output',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='foreign_particles',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='grading_consolidation',
            field=models.CharField(default='NF', max_length=1500),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='husk',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='out_turn',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='pieces',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='process_total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='processed',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='rejection',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='shells',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='processing_lot',
            name='wholes',
            field=models.FloatField(default=0, null=True),
        ),
    ]
